name: database_firebase_helper
description: A Flutter (pure-dart) package to simpler FromMap/ToJson when working with Firebase Firestore
version: 0.2.1+1
repository: https://github.com/kfiross/database_firebase_helper

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  reflectable: ^2.2.9
  cloud_firestore: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

