// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:database_firebase_helper/database_firebase_helper.dart'
    as prefix0;
import 'package:example/model/my_class.dart' as prefix1;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.FirebaseReflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'MyClass',
            r'.MyClass',
            7,
            0,
            const prefix0.FirebaseReflector(),
            const <int>[0, 1, 2, 9],
            const <int>[10, 11, 12, 13, 14, 3, 4, 5, 6, 7, 8],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix1.MyClass() : null},
            0,
            0,
            const <int>[],
            const <Object>[prefix0.firebaseReflector],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(
            r'mId',
            32773,
            0,
            const prefix0.FirebaseReflector(),
            -1,
            1,
            1,
            const <int>[],
            const <Object>[prefix0.Id]),
        r.VariableMirrorImpl(
            r'mName',
            32773,
            0,
            const prefix0.FirebaseReflector(),
            -1,
            1,
            1,
            const <int>[],
            const <Object>[const prefix0.MapTo('name')]),
        r.VariableMirrorImpl(
            r'mAge',
            32773,
            0,
            const prefix0.FirebaseReflector(),
            -1,
            2,
            2,
            const <int>[],
            const <Object>[const prefix0.MapTo('age')]),
        r.ImplicitGetterMirrorImpl(const prefix0.FirebaseReflector(), 0, 3),
        r.ImplicitSetterMirrorImpl(const prefix0.FirebaseReflector(), 0, 4),
        r.ImplicitGetterMirrorImpl(const prefix0.FirebaseReflector(), 1, 5),
        r.ImplicitSetterMirrorImpl(const prefix0.FirebaseReflector(), 1, 6),
        r.ImplicitGetterMirrorImpl(const prefix0.FirebaseReflector(), 2, 7),
        r.ImplicitSetterMirrorImpl(const prefix0.FirebaseReflector(), 2, 8),
        r.MethodMirrorImpl(r'', 64, 0, -1, 0, 0, const <int>[], const <int>[],
            const prefix0.FirebaseReflector(), const []),
        r.MethodMirrorImpl(r'==', 131074, null, -1, 3, 3, const <int>[],
            const <int>[3], const prefix0.FirebaseReflector(), const []),
        r.MethodMirrorImpl(r'toString', 131074, null, -1, 1, 1, const <int>[],
            const <int>[], const prefix0.FirebaseReflector(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            65538,
            null,
            null,
            null,
            null,
            const <int>[],
            const <int>[4],
            const prefix0.FirebaseReflector(),
            const []),
        r.MethodMirrorImpl(r'hashCode', 131075, null, -1, 2, 2, const <int>[],
            const <int>[], const prefix0.FirebaseReflector(), const []),
        r.MethodMirrorImpl(
            r'runtimeType',
            131075,
            null,
            -1,
            4,
            4,
            const <int>[],
            const <int>[],
            const prefix0.FirebaseReflector(),
            const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'_mId',
            32870,
            4,
            const prefix0.FirebaseReflector(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_mName',
            32870,
            6,
            const prefix0.FirebaseReflector(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_mAge',
            32870,
            8,
            const prefix0.FirebaseReflector(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            32774,
            10,
            const prefix0.FirebaseReflector(),
            -1,
            5,
            5,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            12,
            const prefix0.FirebaseReflector(),
            -1,
            6,
            6,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[prefix1.MyClass, String, int, bool, Type, Object, Invocation],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'mId': (dynamic instance) => instance.mId,
        r'mName': (dynamic instance) => instance.mName,
        r'mAge': (dynamic instance) => instance.mAge
      },
      {
        r'mId=': (dynamic instance, value) => instance.mId = value,
        r'mName=': (dynamic instance, value) => instance.mName = value,
        r'mAge=': (dynamic instance, value) => instance.mAge = value
      },
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(
            r'',
            Uri.parse(r'reflectable://0/'),
            const prefix0.FirebaseReflector(),
            const <int>[],
            {},
            {},
            const [],
            null)
      ],
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
